### ISSUE TITLE
Alarms set by AlarmManager are delayed

### ISSUE THREAD

**Issue by frankFic** [pfleidi/yaxim#203]
Hi, I noticed that `AlarmManager.set` is used in [XMPPService](https://github.com/pfleidi/yaxim/blob/7d7e3dc11ee6964c519ff0127eecb66e6ed34ec6/src/org/yaxim/androidclient/service/XMPPService.java#L492) to schedule reconnect and in [SmackableImp](https://github.com/pfleidi/yaxim/blob/9345782648eef3c45096db4053d23d1aac4bd759/src/org/yaxim/androidclient/service/SmackableImp.java#L1142) to register an alarm of timeout. For your information, starting from API 19, alarms set by this API will not be sent at the exact time specified. ([doc](https://developer.android.com/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent))). After API 11, using setExact instead will schedule an exact alarm instead.

**Comment by ge0rg** [comment]
Thanks for the information. Inexact timers are sufficient for most of yaxim's tasks, because it's not about getting called in the right second, but merely about getting reconnected eventually.

Unless there are specific problems that can not be fixed by excluding yaxim from the "battery savings" of modern Android, I don't see an urgent need to act here.

**Comment by frankFic** [comment]
Thanks a lot for your explanation.
