### ISSUE TITLE
Incomplete unread conversation notifications displayed on Android Auto

### ISSUE THREAD

**Issue by marveljy** [pfleidi/yaxim#228]
## Issue Description
  When the phone  installing yaxim connects to the car supporting Android Auto, yaxim can not display correct message count user received. Yaxim's messages will reach at Android Auto,  but they will not be organized correctly. If the user of yaxim receives multiple messages on phone, Android Auto will prompt him that "a new message" instead of "N new messages" to read.
## Root Cause
  Unread conversation builder only adds a combination message with multiple message strings instead of add multiple messages.
## Fix
  Adding a loop outside the API **addMessage()**.

**Comment by ge0rg** [comment]
Thanks very much for the catch and the contribution. The notification code has grown historically and is in a pretty sad state (it's based only on the data sent directly from the service, and needs a major revamp to instead load the unread messages from SQLite/ContentProvider).

## Patch Review

I've had a look at your code, and I have two questions:
* all the current code is segregating messages (and notifications, including UnreadConversation.Builder), by sender JID; in your patch I only see one global ArrayList
* there is no provision for cleaning up the message list when one (or all) notification is tapped, so messages will come back.

To clean this up, you'd have to at least make it a HashMap of JID -> ArrayList<String>, and to clean up in `resetNotificationCounter()`.

## Alternative Suggestion
The current code base is (historically) already using three different maps to store IDs (`notificationId`), number of unread messages (`notificationCount`) and the actual payload (`notificationBigText`). It would be great to refactor these three maps into one map of dumb objects, storing:
* the ID
* an ArrayList<SpannableStringBuilder> of the individual messages (or even better: an ArrayList of timestamp + SpannableStringBuilder)
* (maybe) a SpannableStringBuilder with the concatenated message, so it doesn't need to be re-created each time. But that is probably rather cheap anyway.

The `notificationCount` would be replaced by the ArrayList length, and you could iterate over the ArrayList to properly populate the `ucb`.

## Remaining Issues

There is still one unsolved issue with that, though: last message correction (which is now also supported from yaxim). Currently, a modified message is added multiple times to the notification, which is rather ugly. However, to fix that, the notifyClient() API would need to be extended with a reference to the corrected message, and you'd have to remove the previous message internally.

I think that instead of adding this complexity, the GenericService needs to be rewritten to only take the JID parameter (and flags regarding silence / errors) and to load the actual message content from the ChatProvider. However, this is a larger refactoring which might be a bit much for a first contribution. Please let me know :)
